name: go-cleanarch
on:
  push:
    tags:
      - v*
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:

  cleanarch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5' 
      - name: Install go-cleanarch
        run: go install github.com/roblaszczak/go-cleanarch@latest
      - name: Clean Architecture checker for Golang
        run: go-cleanarch